#83: (test) update test_workflow to add debug step

diff --git a/.github/workflows/test_workflow.yml b/.github/workflows/test_workflow.yml
--- a/.github/workflows/test_workflow.yml
+++ b/.github/workflows/test_workflow.yml
@@ -27,7 +27,27 @@ jobs:
               docker compose exec -T \
               -e APP_ENV=test \
               -e JWT_PASSPHRASE="${{ secrets.JWT_PASSPHRASE_TEST }}" \
-              php php bin/console lexik:jwt:generate-keypair --skip-if-exists --env=test
+              php php bin/console lexik:jwt:generate-keypair --overwrite --env=test
+
+      - name: Check JWT configuration
+        env:
+          JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE_TEST }}
+        run: |
+              if [ -z "$JWT_PASSPHRASE" ]; then
+              echo "JWT_PASSPHRASE is empty"
+              exit 1
+              fi
+      
+              docker compose exec -T \
+              -e APP_ENV=test \
+              -e JWT_PASSPHRASE="$JWT_PASSPHRASE" \
+              php sh -c '
+              test -s config/jwt/private.pem || { echo "private.pem missing"; exit 1; }
+              test -s config/jwt/public.pem || { echo "public.pem missing"; exit 1; }
+      
+              echo "JWT files exist"
+              php bin/console lexik:jwt:check-config --env=test
+              '
 
 #      Préparation de la base de données de test
       - name: Prepare test_database
